version: 3

tasks:
  generate_linux:
    aliases:
     - gen_linux
    desc: "Generate code from proto files"
    cmds:
    - protoc -I proto proto/sso/*.proto --go_out=./gen/go/ --go_opt=paths=source_relative --go-grpc_out=./gen/go/ --go-grpc_opt=paths=source_relative
  generate_windows:
    aliases:
     - gen_windows
    desc: "Generate code from proto files"
    cmds:
    - protoc -I proto .\proto\sso\sso.proto --go_out=.\gen\go --go_opt=paths=source_relative --go-grpc_out=.\gen\go\ --go-grpc_opt=paths=source_relative
